### ISSUE TITLE
Show battery status

### ISSUE THREAD

**Issue by rawcdv** [arcbtc/bowser-bitcoin-hardware-wallet#5]
It would be fun to see how much battery you have left.

Also i saw there are some other batteries that you can attached. 

Still a bit confused how better is this one(https://m5stack.com/products/battery-module) than the one that comes with the grey m5.

**Comment by arcbtc** [comment]
I think its weirdly difficult to get the battery status if memory serves me.
I would just use a USB battery pack or charge only USB wire, rather than order another battery

**Comment by arcbtc** [comment]
Although $7.95 is cheap. I might buy a few and test. Nice find
