### ISSUE TITLE
Question: About entropy

### ISSUE THREAD

**Issue by bitcoinheiro** [arcbtc/bowser-bitcoin-hardware-wallet#6]
Hi Ben, loved your project and been experimenting with it :)

Wanted to ask about the grey M5Stack version that is recommended. Is this because of the 9-axis sensors?
Are they used for entropy? I remember that Stepan mentioned that the Specter DIY random number generator collects entropy from users interaction with the STM board - so  I was wondering if this is the case for the recommendation of the grey m5.

Thanks!

**Comment by arcbtc** [comment]
Bowser uses noise in the RF hardware for entropy, so its similar approach
