### ISSUE TITLE
Obsolete electrumwallettemplate.json

### ISSUE THREAD

**Issue by 78bash** [arcbtc/bowser-bitcoin-hardware-wallet#8]
When I open the electrumwallettemplate.json in Electrum, I am unable to see or send my coins.

**Comment by arcbtc** [comment]
Use the version of electrum specified in this repo

**Comment by 78bash** [comment]
After sunning `./electrum-3.3.8-x86_64.AppImage`
electrum.util.WalletFileException: This version of Electrum is too old to open this wallet.
(highest supported storage version: 18, version of this file: 40)
